# Generated by Django 4.2.3 on 2023-08-01 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagm', '0002_userprofile_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
